// <auto-generated />
using System;
using Equals_Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Equals_Infra.Migrations
{
    [DbContext(typeof(EfCore))]
    partial class EfCoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Equals_Domain.Entites.Acquirer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdAcquirer")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adquirente");

                    b.Property<DateTime>("Created");

                    b.Property<string>("DataProcessamento");

                    b.Property<string>("Estabelecimento");

                    b.Property<string>("Hours");

                    b.Property<string>("PeriodoFinal");

                    b.Property<string>("PeriodoInicial");

                    b.Property<string>("Sequencial");

                    b.Property<string>("TipoRegistro");

                    b.HasKey("Id");

                    b.ToTable("Acquirer");
                });

            modelBuilder.Entity("Equals_Domain.Entites.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdFile")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Hours");

                    b.Property<int>("IdAcquirer");

                    b.Property<string>("StatusFile");

                    b.HasKey("Id");

                    b.HasIndex("IdAcquirer");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Equals_Domain.Entites.File", b =>
                {
                    b.HasOne("Equals_Domain.Entites.Acquirer", "Acquirer")
                        .WithOne("File")
                        .HasForeignKey("Equals_Domain.Entites.File", "IdAcquirer")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
